# Workflow name
name: backend-ci

# Triggers for the workflow
on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:
      
  # Automatic trigger on pull request events targeting the main branch
  pull_request:
    branches:
      - main

# Jobs defined in the workflow
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install pipenv && pip install flake8 

      - name: Run the linter
        run: cd starter/backend && pipenv run lint

  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Install pipenv
        run: pip install pipenv --user      

      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install pipenv && pip install flake8

      - name: Run tests
        run: cd starter/backend && pipenv install pytest && pipenv run test

  build:
    needs: [linting, testing]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10 
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
  
      - name: Install pipenv
        run: python -m pip install --upgrade pip && pip install pipenv && pip install flake8

      - name: Install dependencies
        run: cd starter/backend && pipenv install

      - name: Build docker image
        run: cd starter/backend && docker build --tag mp-backend:${GITHUB_SHA::7} .
        
      - name: Run docker container
        run: cd starter/backend && docker run -p 5000:5000 --name mp-backend -d mp-backend:${GITHUB_SHA::7}